name: LoginSystem
main: fujiwaraizuho\Login
version: er.Î²
api:
  - 3.0.0
  - 3.0.0-ALPHA10
  - 3.0.0-ALPHA11
author: fujiwaraizuho
description: This is LoginSystem
website: https://twitter.com/fujiwaraizuho 