name: UILoginSystem
main: fujiwaraizuho\Login
version: er.β_1.0.0
api:
  - 3.0.0
  - 3.0.0-ALPHA10
  - 3.0.0-ALPHA11
description: This is LoginSystem

author: fujiwaraizuho
website: https://twitter.com/Fujiwaraizuho 

commands:
  updatename:
    usage: "/updatename oldName new Name"
    description: "ログインアカウントデータをアップデートできます。"
  unregister:
    usage: "/unregister"
    description: "ログインアカウントを削除できます。"